id: let_it_sink_culture_document
hints:
  - Enter this website [https://anythink.wilco.gg/culture-document](https://anythink.wilco.gg/culture-document), mark the checkbox and submit it.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "Outstanding work! Mr. Husk is pleased with you."
            delay: 2700
          - text: "In fact, he loved your performance so much that he thinks there’s no way you can maintain this level of commitment."
            delay: 4000
          - text: "So, from what I understand, he’s about to fire you."
            delay: 4000
          - text: 'Unless, that is, you’re willing to [sign the pledge](https://anythink.wilco.gg/culture-document) and commit to a "hardcore" work culture.'
            delay: 3400
          - text: "So do it, :instruction[**sign [the pledge](https://anythink.wilco.gg/culture-document) right now.**]"
            delay: 3000
trigger:
  type: user_event
  params:
    event: culture_doc_submitted
  flowNode:
    do:
      - actionId: finish_step
