id: let_it_sink_is_verified_frontend
learningObjectives:
  - Adding a new field to the Frontend
  - Implementing a design for a new feature
hints:
  - Try to create a new item for a seller that is verified. You should see a **verified** icon (does it match the image posted?)
  - Try to create a new item for a seller that is **not verified** (you should not see an icon). 
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "So, now that the backend is done, we want to **show in the UI, if our sellers are verified or not**."
            delay: 3500
          - text: "To do so, we will need to :instruction[add an image and a 'TOP SELLER' text **after** each seller name on each item in the **feed**]. The image is located in the repo at `/public/verified_seller.svg`"
            delay: 4500
          - text: "Here is a mock of what I need: ![](https://res.cloudinary.com/wilco/image/upload/v1671029257/chat-assets/is_verified_mock_jb1co2.png)"
            delay: 3000
          - text: ":instruction[**Open a PR with those changes**] and I will check it right away."
            delay: 2500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: "Thanks @${user.githubuser}, I'll review the changes right away!"
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: "Looking good ${user.firstName}! You're now able to merge the PR."
                    delay: 1300
            - actionId: github_pr_approve
              params:
                person: head-of-rd
                message: "Looking good @${user.githubuser}! You're now able to merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Umm, something is off. **Make sure all the checks pass** before you try to merge the PR.
                    delay: 2500
                  - text: As always, don't hesitate to **ask for my help** by admitting that you're :input[stuck]{text="I'm stuck!"} and I'm your only hope 👼
                    delay: 2500
            - actionId: github_pr_reject
              params:
                person: head-of-rd
                message: Umm, something is off. **Make sure all the checks pass** before you try to merge the PR. Remember, you can always ask for my help on Snack.
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  backend:
    capabilities:
      - seeds
  frontend:
    capabilities:
      - jest-puppeteer
      - "puppeteer@18.1.0"
    testFile: "is_verified_frontend.test.js"
