id: let_it_sink_culture_document
hints:
  - Did you go to the site and signed the guidelines?
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "Mr. Husk is pleased with you. In fact, he loved your performance so much that he thinks there’s no way you can maintain this level of commitment."
            delay: 4000
          - text: "So, from what I understand, he’s about to fire you."
            delay: 4000
          - text: "Unless, that is, you’re willing to [sign the pledge](https://anythink.wilco.gg/culture-document) and commit to a "hardcore" work culture."
            delay: 2000
          - text: "So do it, :instruction[**sign [it](https://anythink.wilco.gg/culture-document) right now**]."
            delay: 2000
trigger:
  type: user_event
  params:
    event: culture_doc_submitted
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
            - text: "The board understood their mistake and now Enon Husk is being ASKED to leave. We will not be hearing from him again."
              delay: 2000
            - text: "As a parting gift, he leaves you this special, rare, **Let it sink achievement**."
              delay: 2000
      - actionId: finish_step
