id: let_it_sink_is_verified_backend
learningObjectives:
  - Adding a new field to the DB model
  - Adding a new property to the API
hints:
  - Did you add an item to the Anythink website and test your change using the API?
  - Did you add a new field to the DB model?
  - Is the default value of the new field `false`?
startFlow:
  do:
    - actionId: github_commit_file
      paramsFramework:
        node:
          file: ${seeds.js}
          path: "backend/scripts"
          message: "Adding seeds script"
        rails:
          file: ${seeds.rb}
          path: "backend/db"
          message: "Adding seeds script"
        python:
          file: ${seeds.py}
          path: "backend/app/db"
          message: "Adding seeds script"
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "https://media.giphy.com/media/eBCnpuRGBhQGY/giphy-downsized-large.gif"
            delay: 1500
          - text: "Whew, what a couple of weeks it’s been! I mean, when **Evon Husk bought the company**, I expected things to change. But the staggering success he’s had at reducing the employee headcount is downright amazing."
            delay: 4600
          - text: "So, we gathered here today because Evon had a brilliant idea — creating **a new verification program to verify top sellers**"
            delay: 4000
          - text: "How do we intend to verify them? A list Evon made, which we know nothing about."
            delay: 3000
          - text: "Just to be clear, we should disregard the number of things they’ve sold and whether their identities are real. The list is all that matters."
            delay: 5000
          - text: "To do so, we will :instruction[**add a new field called**] ${user.backend === 'python' ? '`is_verified`' : '`isVerified`'} to the User model ${user.database === 'postgresql' ? 'using a DB migration to add the new column to the database' : ''}, and **have it returned from API**${user.backend === 'python' ? '**(the API field should return `isVerified`, without the underscore)**' : ''}"
            delay: 3000
          - text: "To prevent sellers from being verified by mistake, we want each seller to be marked as **not verified** by default."
            delay: 3200
          - text: "So let's **add the field to the User model and the `/items` API endpoint.**"
            delay: 3500
          - text: "Once you're done, :instruction[**open a PR**] with the change and I will review it."
            delay: 3200

githubActions:
  backend:
    capabilities:
      - axios
      - dotenv
      - seeds
    testFile: "is_verified_backend.js"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: That was fast! I'll review the changes right away.
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Wonderful! Looks like the API is working. Now you can :instruction[**merge the PR**] and get ready for your next assignment.
                    delay: 1300
            - actionId: github_pr_approve
              params:
                person: head-of-rd
                message: Nice! Looks like the field is in place. Now you can **merge the PR** and come **back to Snack** once you’re ready.
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Umm, something is off. **Make sure all the checks pass** before you try to merge the PR.
                    delay: 2500
                  - text: As always, don't hesitate to **ask for my help** by admitting that you're :input[stuck]{text="I'm stuck!"} and I'm your only hope 👼
                    delay: 2500
            - actionId: github_pr_reject
              params:
                person: head-of-rd
                message: Umm, something is off. **Make sure all the checks pass** before you try to merge the PR. Remember, you can always ask for my help on Snack.
        github_pr_merged:
          do:
            - actionId: finish_step
