id: let_it_sink_culture_document
hints:
  - Did you go to the site and sign the pledge?
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "Outstanding work! Mr. Husk is pleased with you."
            delay: 2700
          - text: "In fact, he loved your performance so much that he thinks there’s no way you can maintain this level of commitment."
            delay: 4000
          - text: "So, from what I understand, he’s about to fire you."
            delay: 4000
          - text: 'Unless, that is, you’re willing to [sign the pledge](https://anythink.wilco.gg/culture-document) and commit to a "hardcore" work culture.'
            delay: 3400
          - text: "So do it, :instruction[**sign [the pledge](https://anythink.wilco.gg/culture-document) right now.**]"
            delay: 3000
trigger:
  type: user_event
  params:
    event: culture_doc_submitted
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
            - text: https://media.giphy.com/media/OxrQAuM5kKMKHn14ls/giphy.gif
              delay: 3000
            - text: "It’s a good thing you signed the pledge. Unfortunately, you did it too quickly — looks too eager. Please turn in your badge and equipment. Good bye."
              delay: 3000
            - text: "Nevermind that. Evon ran a poll and the users of Anythink decided he should step down. You’re hired again, good for you!✨"
              delay: 4500
            - text: "That said, if anything like this happens again, you probably should tell someone things are amiss."
              delay: 7500
            - text: "This would make you a whistleblower, and it doesn't matter how much the management will want to, turns out it won't be able to retaliate against you."
              delay: 5000
            - text: "You should probably know that in the [US](https://www.whistleblower.gov/) and the [EU](https://commission.europa.eu/aid-development-cooperation-fundamental-rights/your-rights-eu/protection-whistleblowers_en), there are dedicated bodies for these kinds of things."
              delay: 4500
            - text: "While you're waiting for the authorities to swoop in, why not **select your next assignment**?"
              delay: 3500
              components:
                - type: schedule_learning_time
      - actionId: finish_step
