id: let_it_sink_is_verified_frontend
learningObjectives:
  - Adding a new field to the Frontend
hints:
  - Try to create a new item for a seller that is verified
  - Try to create a new item for a seller that is not verified
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "So, now that the backend is in place, we want to show if our sellers are verified or not in the UI."
            delay: 2000
          - text: "To do so we will need to add the 👽 emoji and a 'TOP SELLER' text **after** each seller name on each item on the **feed**."
            delay: 2000
          - text: "Here is a mock of what I need: ![](https://res.cloudinary.com/wilco/image/upload/v1670424303/chat-assets/is_verified_ui_wuemeo.png)"
            delay: 0
          - text: "Open a PR with those changes and I will check it right away."
            delay: 1000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: head-of-rd
                message: "Thanks ${user.githubuser}, I'll review the changes right away!"
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: "Excellent job ${user.firstName}! You're now able to merge the PR."
                    delay: 1300
            - actionId: github_pr_approve
              params:
                person: head-of-rd
                message: "Excellent job ${user.githubuser}! You're now able to merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: head-of-rd
                message: Make sure all checks pass, only then you can merge the PR.

            - actionId: bot_message
              params:
                person: head-of-rd
                messages:
                  - text: Make sure all checks pass, only then you can merge the PR.
                    delay: 2500
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  backend:
    testFile: psql.sql
    cmd:
      - /bin/bash -c "DATABASE_URL=${databaseUrl} ./seeds.sh"
      - psql ${databaseUrl} -f ${testFile} -v ON_ERROR_STOP=1
    paramsFramework:
      node:
        testFile: mongo_seed.js
        cmd:
          - node ${testFile}
  frontend:
    capabilities:
      - jest-puppeteer
      - "puppeteer@18.1.0"
    testFile: "is_verified_frontend.test.js"
