id: lets_sink_culture_document
hints:
  - Did you go to the site and signed the guidelines?
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "${Lodash.startCase('123')} ${JSON.stringify(process.env)} Ok, it seems like everything is working and Enon is pleased, for now."
            delay: 2000
          - text: "The last thing he wants you to do, as one of Anythink's most promising employees (out of the few that didn't quit) is to sign a document in which you commit to its new “hardcore” culture."
            delay: 4000
          - text: "Go [here](https://anythink.wilco.gg/culture-document) to sign the document."
            delay: 2000
trigger:
  type: user_event
  params:
    event: culture_doc_submitted
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
            - text: "The board understood their mistake and now Enon Husk is being ASKED to leave. We will not be hearing from him again."
              delay: 2000
            - text: "As a parting gift, he leaves you this special, rare, **Let's sink achievement**."
              delay: 2000
      - actionId: finish_step
